### PR TITLE
Add Image input components

### PR DESCRIPTION
**Pull request by AnkurChunekar**

### CODE REVIEW

**Review by starver20 — APPROVED** [review]
For the input error, you can also give red border to the input. Rest all looks good

**Review by mohammed-sas — APPROVED** [review]
good to merge

**Comment by RahullRawat** [comment]
looks good ankur. good to merge

**Review by RahullRawat — APPROVED** [review]

**Comment by AnkurChunekar** [comment]
> 

Thanks for your feedback i will make the necessary change

**Pull request merged**
