### PR TITLE
Add Text utilities lists

### PR DESCRIPTION
**Pull request by AnkurChunekar**
Adding some text utilities and some different types of list.

### CODE REVIEW

**Comment by RakshaPawar108** [comment]
Code looks clean and good to merge Ankur. Great work!

**Review by RakshaPawar108 — APPROVED** [review]

**Review by RahullRawat — APPROVED** [review]
All good Ankur. You can merge it

**Review by kart-c — APPROVED** [review]
Looks good Ankur, I would suggest a small refacator to remove unnecessary code in CSS (if it is not intentionally left there)

**Comment by AnkurChunekar** [comment]
> 

Thanks guys, and @kart-c i will look into it ty!

**Pull request merged**
